<?php
/**
 * @category    design
 * @package     default_theexchange
 * @copyright   admaduranga@gmail.com
 * @license     admaduranga@gmail.com
 * @var $this   Mage_Core_Block_Template
 */
?>
<div class="custom_tweets">
    <?php echo $this->getChildHtml('home_our_tweets'); ?>
</div>
<!--<div class="custom_red_line">-->
<!--</div>-->

<div class="custom_red_triangle">

    <img src="<?php echo $this->getSkinUrl('images/footer-red-traingle.png') ?>" />
    <div class="call_us">
        <div class="custom_x_logo">X</div>
        <div class="custom_call_us">
            <div class="label"><?php echo $this->__('Call us on') ?></div>
            <div class="phone_no"><?php echo $this->helper('commonrewrites')->getStoreConfig('phone'); ?></div>
        </div>
    </div>

</div>