<?php
/**
 * @category    design
 * @package     default_theexchange
 * @copyright   admaduranga@gmail.com
 * @license     admaduranga@gmail.com
 */
?>
<?php
/**
 * @see Mage_Core_Block_Template
 */
?>
<div class="footer_social_links">
    <h4><strong><?php echo $this->__('We’re social too!'); ?></strong></h4>
    <ul class="ul-inks">
        <li class="fb">fb</li>
        <li class="twitter">twitter</li>
    </ul>
</div>