<?php
/**
 * @category    design
 * @package     default_theexchange
 * @copyright   admaduranga@gmail.com
 * @license     admaduranga@gmail.com
 */
?>
<?php
/**
 * @see Mage_Core_Block_Template
 */
?>
<div class="footer_social_links">
    <h4><?php echo $this->__('We’re social too!'); ?></h4>
    <?php echo $this->getChildHtml('cms_footer_social_links'); ?>
    <div class="credit-card">
      <h4>We accept all major credit cards</h4>
      <img src="<?php echo $this->getSkinUrl('images/credit_cards.svg') ?>" width="250"/>
    </div>
</div>
