<?php
/**
 *
 * @category    design
 * @package     default_theexchange
 * @copyright   admaduranga@gmail.com
 * @license     admaduranga@gmail.com
 * @var $this   Mage_Newsletter_Block_Subscribe
 */
?>
<div class="block block-subscribe">
    <form action="#" method="post" id="invite-friend-validate-detail">
        <div class="block-content newsletter-subs">
            <div class="form-subscribe-header">
                <label for="newsletter"><?php echo $this->__('Recommend a Friend:') ?></label>
            </div>
            <div class="v-fix">
                <div class="newsletter-input">
                    <input type="text" name="invite_email" id="invite-friend" title="<?php echo $this->__('Recommend a Friend') ?>" placeholder="<?php echo $this->__('Enter your friends email');?> " class="input-text required-entry validate-email" />
                </div>
                <button type="submit" title="<?php echo $this->__('Subscribe') ?>" class="button"><?php echo $this->__('Subscribe') ?></button>
            </div>
        </div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var inviteFriendFormDetail = new VarienForm('invite-friend-validate-detail');
    //]]>
    </script>
</div>
