<div class="custom_footer_wrapper">
    <div class="custom_footer_static_block">
        <?php echo $this->getChildHtml('cms_footer_static'); ?>
    </div>

    <div class="custom_red_line">

    </div>

    <div class="custom_red_triangle">
        <div class="custom_x_logo">X</div>
        <div class="custom_call_us">
            <span>Call us on</span>
            <span class="phone_no"><?php echo $this->helper('commonrewrites')->getStoreConfig('phone'); ?></span>
        </div>
    </div>
</div>