<?php
/**
 *
 * @category    design
 * @package     default_theexchange
 * @copyright   admaduranga@gmail.com
 * @license     admaduranga@gmail.com
 * @var $this   Mage_Newsletter_Block_Subscribe
 */
?>
<div class="block block-subscribe">
    <form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="newsletter-validate-detail">
        <div class="block-content newsletter-subs">
            <div class="form-subscribe-header">
                <label for="newsletter"><?php echo $this->__('Sign Up to Our Newsletter:') ?></label>
            </div>
            <div class="v-fix">
                <div class="newsletter-input">
                    <input type="text" name="email" id="newsletter" title="<?php echo $this->__('Sign up for our newsletter') ?>" class="input-text required-entry validate-email" />
                </div>
                <button type="submit" title="<?php echo $this->__('Subscribe') ?>" class="button"><?php echo $this->__('Subscribe') ?></button>
            </div>
        </div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail');
    //]]>
    </script>
</div>
