<?php
/**
 *
 * @category    design
 * @package     default_theexchange
 * @copyright   admaduranga@gmail.com
 * @license     admaduranga@gmail.com
 * @var $this   Mage_Newsletter_Block_Subscribe
 */
?>
<div class="footer_brand_section">
    <h3><?php echo $this->__('Our Partners'); ?></h3>
    <?php echo $this->getChildHtml('footer_partner_list'); ?>

    <span class="footer-logo">FOOTER_IMAGE</span>
</div>