<?php
/**
 * @author      admaduranga@gmail.com
 * @copyright   admaduranga@gmail.com
 * @var $this   DMS_Productrepairs_Block_Form
 */
?>
<div id="repair_model_wrapper" class="repair_model_wrapper">
    <select class="form-control required-entry"  name="model" id="repair_model">
        <?php foreach ($this->getProductModelsFromBrand() as $modelId => $model): ?>
            <option value="<?php echo $modelId; ?>"><?php echo $model; ?></option>
        <?php endforeach; ?>
    </select>
</div>