<?php
/**
 * @author      admaduranga@gmail.com
 * @copyright   admaduranga@gmail.com
 * @var $this   DMS_Productrepairs_Block_Form
 */
?>
<div class="dms-productrepair page-wrapper">
    <h1><?php echo $this->__('Fix It'); ?></h1>
    <p class="page-description">
        <?php echo $this->getPageDescription(); ?>
    </p>
    <div class="row">
        <div class="wrapper">
            <div class="img-wrapper col-lg-5">
                <img src="<?php echo Mage::getBaseUrl('media').'/wysiwyg/dms/productrepairs/repair-form.jpg'?>" alt="Repair Page"/>
            </div>
            <div class="repair-form col-lg-6 form-list">
                <form name="product_repair_form" id="product_repair_form" method="POST" action="<?php echo $this->getUrl('phone-repairs/index/book');?>" enctype='multipart/form-data'>
                    <div class="col2-set">
                        <div class="form-group col-1 col-lg-6 col-md-6 col-xs-12">
                            <label for="repair_brand"><?php echo $this->__('Brand') ?><em>*</em></label>
                            <select class="form-control required-entry"  name="brand" id="repair_brand">
                                <option value=""><?php echo $this->__('Select Your Brand...'); ?></option>
                                <?php foreach ($this->getBrands() as $brand): ?>
                                    <option value="<?php echo $brand->getName(); ?>"><?php echo $brand->getName(); ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                        <div class="form-group col-1 col-lg-6 col-md-6 col-xs-12">
                            <label for="repair_model"><?php echo $this->__('Model') ?><em>*</em></label>
                            <input type="text" class="form-control required-entry"  name="model" id="repair_model" placeholder="Model" value="">
                        </div>
                    </div>
                    <div class="form-group ">
                        <label for="repair_fault"><?php echo $this->__('Fault') ?><em>*</em></label>
                        <input type="text" class="form-control required-entry"  name="fault" id="repair_fault" placeholder="Fault" value="">
                    </div>

                    <div class="form-group">
                        <label for="repair_fault_description"><?php echo $this->__('Fault Description') ?><em>*</em></label>
                        <textarea class="form-control required-entry"  name="fault" id="repair_fault_description" placeholder="Fault Description" value=""></textarea>
                    </div>

                    <div class="form-group">
                        <label for="repair_fullname"><?php echo $this->__('Full Name') ?><em>*</em></label>
                        <input type="text" class="form-control required-entry"  name="full_name" id="repair_fullname" placeholder="Full Name" value="">
                    </div>

                    <div class="form-group">
                        <label for="repair_email"><?php echo $this->__('Email') ?><em>*</em></label>
                        <input type="text" class="form-control required-entry validate-email"  name="email" id="repair_email" placeholder="Email" value="">
                    </div>

                    <div class="form-group">
                        <label for="repair_contact"><?php echo $this->__('Contact No') ?><em>*</em></label>
                        <input type="text" class="form-control required-entry validate-number"  name="contact_no" id="repair_contact" placeholder="Contact No" value="">
                    </div>

                    <div class="form-group">
                        <label for="repair_image"><?php echo $this->__('Attachment (jpg or png less than 1MB)') ?></label>
                        <input type="file" class="form-control"  name="image" id="repair_image" value="">
                    </div>

                    <div class="form-group">
                        <div class="submit-button-wrapper">
                            <input type="submit" name="submit" value="Book Now" id="submit_repair_form">
                        </div>
                    </div>

                <span class="required-field-notification">
                    <?php echo $this->__('Required field'); ?><em>*</em>
                </span>
                </form>
            </div>
        </div>
    </div>

</div>

<script type="text/javascript">
    //< ![CDATA[
    var customForm = new VarienForm('product_repair_form');
    //]]>
</script>