<style>
    .hd {
        background-color: #D2B9D3;
        padding: 3px;
        color: #FFFFFF;
        font-size: 14px;
        font-weight: bold;
    }

    .close {
        text-decoration: none;
        color: #FFFFFF;
        font-weight: none;
        font-size: 10px;
        vertical-align: middle;
    }

    td.share a {
        border: 0;
        text-decoration: none;
    }

    td.share a img {
        border: 0;
        text-decoration: none;
        padding: 3px;
        height: 30px;
        width: 30px;
    }
</style>

<?php
$_product = $this->getProduct();
$_productId = $_product->getId();
?>

<div class="quickview-main">
    <a href="#" class="close"><?php echo $this->__('Close') ?></a>
    <div class="quickview-wrapper">
        <div class="row line-2">
            <div class="product-img-box" style="margin:5px; width=265px; vertical-align:top;">
                <a href="<?php echo $_product->getProductUrl(); ?>"
                   title="<?php echo $_product->getName(); ?>" class="quickview-product-url">
                    <p class="product-image" style="vertical-align:top;">
                        <img title="<?php echo $_product->getName() ?>"
                             alt="<?php echo $_product->getName() ?>"
                             src="<?php echo $_product->getImageUrl() ?>"></p>
                </a>
            </div>
            <div class="product-shop">
                <div class="product-name">
                    <a href="<?php echo $_product->getProductUrl(); ?>"
                       title="<?php echo $_product->getName(); ?>" class="quickview-product-url">
                        <h2><?php echo $_product->getName() ?></h2>
                    </a>
                </div>
                <div class="reveiew_summary_quickview">
                    <?php echo $this->getChild('quickview_review')->getSummaryHtml($_product, 'stars', true);?>
                </div>

                <div class="std short-desc"><?php echo $_product->getShortDescription() ?></div>
<!--                <div class="std long-desc">--><?php //echo $_product->getDescription() ?><!--</div>-->

                <div class="price-box">
                    <span class="regular-price">
                        <span class="price"><?php echo $this->helper('checkout')->formatPrice($_product->getPrice()); ?></span>
                    </span>

                    <?php if ($_product->isSaleable()) : ?>
                        <?php if ($productQty = $_product->getStockItem()->getQty()) : ?>
                            <p class="availability in-stock">
                                <span><span class="qty"><?php echo intVal($productQty) ?></span> <?php echo $this->__('in stock online') ?></span>
                            </p>
                        <?php else: ?>
                            <p class="availability out-stock">
                                <span><?php $this->__('temporarily out of stock.')?></span></p>;
                        <?php endif; ?>
                    <?php endif; ?>
                </div>



            </div>
        </div>

        <div class="row line-3">
            <div class="quickview-full-spec"><a
                    href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->__('Full specification'); ?></a>
            </div>
            <div class="add-to-cart">
                <label for="qty"><?php echo $this->__('Qty')?></label>
                <div class="add-qty">
                    <div class="qty-wrapper">
                        <input type="number" class="input-text qty" title="Qty" value="1" maxlength="12" id="qty_<?php echo $_productId ?>" name="qty">
                    </div>

                </div>


                <button class="button btn-cart btn" id="<?php echo $_product->getId() ?>"
                        title="Add to basket" type="button">
                    <?php echo $this->__('Add to basket'); ?>
                </button>
                <span style="padding:3px;" id="addingCart_<?php echo $_productId ?>"></span>
            </div>
        </div>
    </div>

    <script>

        jQuery(document).ready(function () {

            var baseUrl = '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK); ?>';
            jQuery('.button').click(function () {
                var pid = jQuery(this).attr('id');
                var qty = jQuery('#qty_' + pid).val();

                showLoader('.quickview-main');
               // jQuery('#addingCart_' + pid).html('Adding to cart...');
//            jQuery.ajax({
//                type: "POST",
//                url: baseUrl + "checkout/cart/add",
//                data: 'product=' + pid + '&qty=' + qty,
//                success: function (msg) {
//                    jQuery('#addingCart_' + pid).html('Added to cart.');
//                    cartInfo();
//                }
//            });
                jQuery.ajax({
                    type: "GET",
                    url: "<?php echo $this->getAddToCartUrl($_product) ?>qty/" + qty,
                    success: function (msg) {
                        jQuery('#addingCart_' + pid).html('Added to cart.');
                        cartInfo();
                        jQuery('#product_data').empty();
                        jQuery('#mask, .window').hide();
                        removeOverlay(this);
                        hideLoader('.quickview-main .line-2');
                    }
                });
            });

            function cartInfo() {
                jQuery('#cartInfo').empty().html('Updating cart info...');
                jQuery.ajax({
                    type: "POST",
                    dataType:"json",
                    url: baseUrl + "productbook/index/cartinfo",
                    // data: 'product='+pid+'&qty='+qty,
                    success: function (msg) {
                        console.log(msg);
                        console.log(msg.cart_count);
                        if (msg.cart_count) {
                            jQuery('.top-link-cart').find('.cart-count').html(msg.cart_count);
                        }
                        jQuery('#cartInfo').empty().html(msg);
                    }
                });
            }

            //if close button is clicked
            jQuery('.window .close').click(function (e) {
                //Cancel the link behavior
                e.preventDefault();
                jQuery('#product_data').empty();
                jQuery('#mask, .window').hide();
                removeOverlay(this);
            });

        });

    </script>
</div>