<?php
$_products = $this->getProductList();
if ($_products && count($_products)) :?>
    <div class="product-widget-main">
        <div class="widget widget-static-block product-widget">
            <h2><?php echo str_replace('|',' ',$this->getDisplayTitle()) ?></h2>
            <div class="best-seller">
                <div class="productScrollLeft"></div>
                <div class="productScrollWrap">
                    <ul class="bestseller_wrapper" >
                        <?php
                        $_commonHelper = $this->helper('modulerewrites');

                        foreach ($_products as $_product) :
                            $_isSaleable = $_product->getData('stock_status');
                            if($_product->getIsNoncore() && !$_isSaleable) continue;
                            ?>
                            <li class="bestseller_productwrapper">
                                <div class="bestseller_imagewrapper">
                                    <a href="<?php echo Mage::getUrl().$_product->getUrlPath() ?>">
                                        <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(216,258);?>" pinimg="<?php echo $this->helper('catalog/image')->init($_product, 'small_image'); ?>"/>
                                    </a>
                                </div>
                            </li>
                        <?php
                        endforeach;
                        ?>
                    </ul>
                </div>
                <div class="productScrollRight"></div>
            </div>
        </div>
        <div class="quickview-view-wrapper-place"></div>
    </div>
<?php endif;?>
